# Generated by Django 4.2.4 on 2023-08-24 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_room_current_song"),
        ("spotify", "0002_votes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Votes",
            new_name="Vote",
        ),
    ]
