# Generated by Django 4.2 on 2023-06-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest_canpause',
            new_name='guest_can_pause',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='votes_toskip',
            new_name='votes_to_skip',
        ),
    ]
